fix(prefer-importing-jest-globals): ensure imports aren't inserted in…
jest-community/eslint-plugin-jest pull request #1645
Opened 2024-08-29 23:54 UTC by ejzimmer

The current fixer implementation for prefer-importing-jest-globals inserts the `import` directly before the reporting node. This works fine when the reporting node is a function call.
```
describe(...)
```
results in
```
import { describe } from 'jest/globals';
describe(...)
```

But it breaks when the reporting node is part of a variable declaration
```
const onClick = jest.fn();
```
results in 
```
const onClick = import { jest } from '@jest/globals';
jest.fn();
```

This change updates the fixer so that when the file is a module, it inserts the import at the top of the file.
```
console.log('foo');
const onClick = jest.fn();
```
results in 
```
import { jest } from '@jest/globals';
console.log('foo')
const onClick = jest.fn();
```

And when it's a script, it inserts the import immediately before the current statement.
```
console.log('foo');
const onClick = jest.fn();
```
results in 
```
console.log('foo')
const { jest } = require('@jest/globals');
const onClick = jest.fn();
```

Why didn't I just put the import at the top in both cases? It would have broken a couple of tests, eg:
```
      code: dedent`
            const source = 'globals';
            const {describe} = require(\`@jest/\${source}\`);
            describe("suite", () => {
              test("foo");
              expect(true).toBeDefined();
            })
          `,
      // todo: this shouldn't be indenting the "test"
      output: dedent`
            const source = 'globals';
            const {describe} = require(\`@jest/\${source}\`);
            describe("suite", () => {
              const { expect, test } = require('@jest/globals');
            test("foo");
              expect(true).toBeDefined();
            })
          `,
```

2024-08-30 01:35 UTC, G-Rath requested changes
could you undo all the unneeded indenting changes in the test cases please?

2024-08-30 03:20 UTC, ejzimmer commented
> could you undo all the unneeded indenting changes in the test cases please?

Oh yikes, yeah, clearly prettier did not have my back.

2024-08-30 04:00 UTC, G-Rath approved these changes
this looks fine, though I'd appreciate if you could cleanup the intending on the new cases (sorry, Prettier doesn't handle javascript-in-javascript blocks 😅) and explain a bit more about

> Why didn't I just put the import at the top in both cases? Because it would have broken a couple of tests, eg:

I don't follow how it would have broken the test you've mentioned

2024-09-02 22:11 UTC, ejzimmer commented
> > Why didn't I just put the import at the top in both cases? Because it would have broken a couple of tests, eg:
> 
> I don't follow how it would have broken the test you've mentioned

That test places the `require` inside a function, and I just wasn't sure if that was important. Like, is requiring different modules inside of different functions something people do with commonjs modules? (I work almost exclusively with esmodules where obviously that just isn't a thing)

2024-09-02 22:23 UTC, G-Rath commented
What matters for us (mostly) is if its syntactically valid e.g. if we would end up duplicating a `const` in the same scope, that'd be bad; technically rules don't need to care about style because those that care should have lint rules that style anyway e.g. we don't need to bother figuring out if we should be using double or single quotes, or about placing semicolons.

We still do some of that stuff when it's easy because it can still be nice to do, but if a particular thing is very complex then we can choose not to take on that complexity.

In this case though I think putting it at the top of the file is the right move as it's likely we'll have multiple references throughout nested functions, though I think we should be fine to just always put the require at the very top of the file like you're doing for `import`s (but it's probably not the end of the world?)

2024-09-04 19:16 UTC, merged