feat: create max-nested-describe rule
jest-community/eslint-plugin-jest pull request #845
Opened 2021-05-23 15:37 UTC by dominictwlee

Resolves #362

The idea is the same as the above issue. I changed the rule name and options to something more consistent with the `max-nested-callbacks` rule.

2021-05-23 19:32 UTC, G-Rath requested changes

2021-05-23 19:32 UTC, G-Rath commented on src/rules/utils.ts
> +export const isCallExpression = (
We don't need this utility function, as you can just do `node?.type === AST_NODE_TYPES.CallExpression`

2021-05-23 19:32 UTC, G-Rath commented on src/rules/max-nested-describe.ts
> +          {
Let's keep things simple and just support an object

2021-05-23 19:32 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +ruleTester.run('max-nested-describe', rule, {
Could you add a test for `{ max: 0 }`

2021-05-24 19:49 UTC, dominictwlee commented
Thanks for the review @G-Rath, I've made the changes according to your comments.

2021-05-24 19:56 UTC, G-Rath requested changes
Cheers, this is looking good! Just got some documentation fixes, and if you could add a few modifier & `.each` tests that'd be great!

2021-05-24 19:56 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +ruleTester.run('max-nested-describe', rule, {
Could you chuck in a few tests for prefixed & modified describes? (i.e `fdescribe`, `describe.skip` - feel free to just chuck these into some of the existing tests), and one of each version of `describe.each`.

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +      "max": 3
```suggestion
      "max": 2
```

nit: I think it's better if we use the default value here.

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +      expect(getSomething().toBe('Something'));
```suggestion
      expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +      expect(getSomething().toBe('Something'));
```suggestion
      expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +    expect(getSomething().toBe('Something'));
```suggestion
    expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +        expect(getSomething().toBe('Something'));
```suggestion
        expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +        expect(getSomething().toBe('Something'));
```suggestion
        expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +        expect(getSomething().toBe('Something'))
```suggestion
        expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +        expect(getSomething().toBe('Something'))
```suggestion
        expect(getSomething()).toBe('Something');
```

2021-05-24 19:56 UTC, G-Rath commented on docs/rules/max-nested-describe.md
> +        expect(getSomething().toBe('Something'))
```suggestion
        expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +                  expect(getSomething().toBe('Something'))
```suggestion
                  expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +                expect(getSomething().toBe('Something'))
```suggestion
                expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +                expect(getSomething().toBe('Something'))
```suggestion
                expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +                expect(getSomething().toBe('Something'))
```suggestion
                expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +                expect(getSomething().toBe('Something'))
```suggestion
                expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +            expect(getSomething().toBe('Something'))
```suggestion
            expect(getSomething()).toBe('Something');
```

2021-05-24 20:42 UTC, G-Rath commented on src/rules/__tests__/max-nested-describe.test.ts
> +            expect(getSomething().toBe('Something'))
```suggestion
            expect(getSomething()).toBe('Something');
```

2021-05-24 20:49 UTC, dominictwlee commented
My bad with the brackets! been a long day my eyes must be going fuzzy.

2021-05-24 20:53 UTC, G-Rath approved these changes
Awesome! No worries about the brackets - thanks for putting up with all my nitty requests 😄

2021-05-24 20:53 UTC, G-Rath commented on src/rules/max-nested-describe.ts
> +        'Too many nested describe calls ({{depth}}). Maximum allowed is {{max}}.',
```suggestion
        'Too many nested describe calls ({{ depth }}). Maximum allowed is {{ max }}.',
```

nit: I typically put spaces around the names (and so most if not all of our rules are like this) - we don't have a lint rule for enforcing this, but would be nice to be consistent.

2021-05-24 20:59 UTC, G-Rath commented
I'm now wondering if `2` is a good max, given that `max-nested-callbacks` has a max of `10`.

Thinking about the tests I've written, I easily have more than two nested `describe`s, and think you would easily hit that with class/method tests:

```
describe('MyClass', () => {
  describe('#doSomethingWithDate', () => {
    describe('when an error happens', () => {
       ...
    });

    describe('when given a number', () => {
      it('parses it as a date', () => {
         ...
      });
    });

    describe('when the date is in the future', () => {
       ...
    });
  });
});
```

I'm not overly fussed about having the perfect default, but wouldn't mind hearing if @SimenB has any opinions on what a good nested level might be.

2021-05-24 21:07 UTC, dominictwlee commented
> I'm now wondering if `2` is a good default max, given that `max-nested-callbacks` has a max of `10`.
> 
> Thinking about the tests I've written, I easily have more than two nested `describe`s, and think you would easily hit that with class/method tests:
> 
> ```
> describe('MyClass', () => {
>   describe('#doSomethingWithDate', () => {
>     describe('when an error happens', () => {
>        ...
>     });
> 
>     describe('when given a number', () => {
>       it('parses it as a date', () => {
>          ...
>       });
>     });
> 
>     describe('when the date is in the future', () => {
>        ...
>     });
>   });
> });
> ```
> 
> I'm not overly fussed about having the perfect default, but wouldn't mind hearing if @SimenB has any opinions on what a good nested level might be.

Yeah it's pretty subjective so probably depends on the respective individuals/teams.Though I do think 10 is probably a bit much for nested describes.

2021-06-29 14:58 UTC, dominictwlee commented
@SimenB @G-Rath Hey just following up on this. Any thoughts on the dafaults?

2021-06-29 20:00 UTC, G-Rath commented
@dominictwlee sorry I've been very busy recently, both working on some core changes to `eslint-plugin-jest` (currently, looking at using `settings` for configuring rules) and with other work stuff 😅

Currently I think 5 is probably a good default, as it leaves you with 3 levels of nesting after a class describe + method describe.

2021-07-04 22:04 UTC, dominictwlee commented
> @dominictwlee sorry I've been very busy recently, both working on some core changes to `eslint-plugin-jest` (currently, looking at using `settings` for configuring rules) and with other work stuff 
> 
> Currently I think 5 is probably a good default, as it leaves you with 3 levels of nesting after a class describe + method describe.

@G-Rath  I've updated the default max to 5, and added a few tests + examples in docs for this.

2021-07-21 16:33 UTC, dominictwlee commented
@G-Rath Just following up on this periodically, let me know if anything needs to change.

2021-07-21 20:45 UTC, G-Rath commented
@dominictwlee cheers, lets land it

2021-07-21 20:45 UTC, merged